/**
 * Generated by @openapi-codegen
 *
 * @version 1.1.4
 */
import type * as Schemas from "./githubSchemas";

export type AccessToken = string;

export type AccountId = number;

export type Actor = string;

export type AlertNumber = Schemas.AlertNumber;

/**
 * @default false
 */
export type All = boolean;

export type AppSlug = string;

export type ArtifactId = number;

export type AssetId = number;

export type AuditLogAfter = string;

export type AuditLogBefore = string;

export type AuditLogInclude = "web" | "git" | "all";

export type AuditLogOrder = "desc" | "asc";

export type AuditLogPhrase = string;

export type AuthorizationId = number;

export type Before = string;

export type Branch = string;

export type CardId = number;

export type CheckName = string;

export type CheckRunId = number;

export type CheckSuiteId = number;

export type ClientId = string;

export type ColumnId = number;

export type CommentNumber = number;

export type CommentId = number;

export type CommitSha = string;

export type Count = number;

export type DeploymentId = number;

/**
 * @default desc
 */
export type Direction = "asc" | "desc";

export type DiscussionNumber = number;

export type Enterprise = string;

export type EnvironmentName = string;

export type Event = string;

export type GistId = string;

export type GitRef = Schemas.CodeScanningRef;

export type GpgKeyId = number;

export type GrantId = number;

export type HookId = number;

export type InstallationId = number;

export type InvitationId = number;

export type IssueNumber = number;

export type JobId = number;

export type KeyId = number;

export type Labels = string;

export type MigrationId = number;

export type MilestoneNumber = number;

/**
 * @default desc
 */
export type Order = "desc" | "asc";

export type Org = string;

export type OrgId = number;

export type Owner = string;

export type PackageName = string;

export type PackageType =
  | "npm"
  | "maven"
  | "rubygems"
  | "docker"
  | "nuget"
  | "container";

export type PackageVersionId = number;

/**
 * @default 1
 */
export type Page = number;

/**
 * @default false
 */
export type Participating = boolean;

/**
 * @default day
 */
export type Per = "" | "day" | "week";

/**
 * @default 30
 */
export type PerPage = number;

export type PlanId = number;

export type ProjectId = number;

export type PullNumber = number;

export type ReactionId = number;

export type ReleaseId = number;

export type Repo = string;

export type RepoName = string;

export type RepositoryId = number;

export type ReviewId = number;

export type RunId = number;

export type RunnerGroupId = number;

export type RunnerId = number;

export type ScimGroupId = string;

export type ScimUserId = string;

export type SecretName = string;

export type Since = string;

export type SinceOrg = number;

export type SinceRepo = number;

export type SinceUser = number;

/**
 * @default created
 */
export type Sort = "created" | "updated";

export type StartIndex = number;

export type Status = "queued" | "in_progress" | "completed";

export type TeamId = number;

export type TeamSlug = string;

export type ThreadId = number;

export type ToolGuid = Schemas.CodeScanningAnalysisToolGuid;

export type ToolName = Schemas.CodeScanningAnalysisToolName;

export type Username = string;

export type WorkflowId = number | string;

export type WorkflowRunBranch = string;

export type WorkflowRunStatus =
  | "completed"
  | "action_required"
  | "cancelled"
  | "failure"
  | "neutral"
  | "skipped"
  | "stale"
  | "success"
  | "timed_out"
  | "in_progress"
  | "queued"
  | "requested"
  | "waiting";
