/**
 * Generated by @openapi-codegen
 *
 * @version 1.1.4
 */
import type * as Schemas from "./githubSchemas";

export type AccountId = number;

export type ActionsCacheKey = string;

export type ActionsCacheKeyRequired = string;

/**
 * @default last_accessed_at
 */
export type ActionsCacheListSort =
  | "created_at"
  | "last_accessed_at"
  | "size_in_bytes";

export type Actor = string;

export type AlertNumber = Schemas.AlertNumber;

/**
 * @default false
 */
export type All = boolean;

export type AppSlug = string;

export type ArtifactId = number;

export type AssetId = number;

export type AttemptNumber = number;

export type AutolinkId = number;

/**
 * @format date-time
 */
export type Before = string;

export type Branch = string;

export type BranchPolicyId = number;

export type CacheId = number;

export type CardId = number;

export type CheckName = string;

export type CheckRunId = number;

export type CheckSuiteId = number;

export type ClientId = string;

export type CodespaceName = string;

export type ColumnId = number;

export type CommentId = number;

export type CommentNumber = number;

export type CommitSha = string;

/**
 * @format date-time
 */
export type Created = string;

export type Cursor = string;

export type DeliveryId = number;

export type DependabotAlertCommaSeparatedEcosystems = string;

export type DependabotAlertCommaSeparatedManifests = string;

export type DependabotAlertCommaSeparatedPackages = string;

export type DependabotAlertCommaSeparatedSeverities = string;

export type DependabotAlertCommaSeparatedStates = string;

export type DependabotAlertNumber = Schemas.AlertNumber;

export type DependabotAlertScope = "development" | "runtime";

/**
 * @default created
 */
export type DependabotAlertSort = "created" | "updated";

export type DeploymentId = number;

/**
 * @default desc
 */
export type Direction = "asc" | "desc";

export type DiscussionNumber = number;

export type Enterprise = string;

export type EnvironmentName = string;

export type Event = string;

/**
 * @default false
 */
export type ExcludePullRequests = boolean;

export type ExportId = string;

export type GistId = string;

export type GitRef = Schemas.CodeScanningRef;

export type GpgKeyId = number;

export type HookId = number;

export type InstallationId = number;

export type InvitationId = number;

export type IssueNumber = number;

export type JobId = number;

export type KeyId = number;

export type Labels = string;

export type ManifestPath = string;

export type MigrationId = number;

export type MilestoneNumber = number;

/**
 * @default desc
 */
export type Order = "desc" | "asc";

export type Org = string;

export type OrgSecurityProductEnablement = "enable_all" | "disable_all";

export type Owner = string;

export type PackageName = string;

export type PackageType =
  | "npm"
  | "maven"
  | "rubygems"
  | "docker"
  | "nuget"
  | "container";

export type PackageVersionId = number;

export type PackageVisibility = "public" | "private" | "internal";

/**
 * @default 1
 */
export type Page = number;

export type PaginationAfter = string;

export type PaginationBefore = string;

/**
 * @default 30
 * @maximum 100
 * @minimum 1
 */
export type PaginationFirst = number;

/**
 * @maximum 100
 * @minimum 1
 */
export type PaginationLast = number;

/**
 * @default false
 */
export type Participating = boolean;

/**
 * @default day
 */
export type Per = "day" | "week";

/**
 * @default 30
 */
export type PerPage = number;

export type PlanId = number;

export type ProjectId = number;

export type PullNumber = number;

export type ReactionId = number;

export type ReleaseId = number;

export type Repo = string;

export type RepoName = string;

export type RepoRequiredWorkflowId = number;

export type RepositoryId = number;

export type RepositoryIdInQuery = number;

export type RequiredWorkflowId = number;

export type ReviewId = number;

export type RunId = number;

export type RunnerId = number;

export type RunnerLabelName = string;

export type SecretName = string;

export type SecretScanningAlertResolution = string;

export type SecretScanningAlertSecretType = string;

/**
 * @default created
 */
export type SecretScanningAlertSort = "created" | "updated";

export type SecretScanningAlertState = "open" | "resolved";

export type SecretScanningPaginationAfterOrgRepo = string;

export type SecretScanningPaginationBeforeOrgRepo = string;

export type SecurityProduct =
  | "dependency_graph"
  | "dependabot_alerts"
  | "dependabot_security_updates"
  | "advanced_security"
  | "secret_scanning"
  | "secret_scanning_push_protection";

/**
 * @format date-time
 */
export type Since = string;

export type SinceOrg = number;

export type SinceRepo = number;

export type SinceUser = number;

/**
 * @default created
 */
export type Sort = "created" | "updated";

export type SshSigningKeyId = number;

export type Status = "queued" | "in_progress" | "completed";

export type TagProtectionId = number;

export type TeamId = number;

export type TeamSlug = string;

export type ThreadId = number;

export type ToolGuid = Schemas.CodeScanningAnalysisToolGuid;

export type ToolName = Schemas.CodeScanningAnalysisToolName;

export type Username = string;

export type VariableName = string;

/**
 * @default 10
 */
export type VariablesPerPage = number;

export type WorkflowId = number | string;

export type WorkflowRunBranch = string;

export type WorkflowRunCheckSuiteId = number;

export type WorkflowRunHeadSha = string;

export type WorkflowRunStatus =
  | "completed"
  | "action_required"
  | "cancelled"
  | "failure"
  | "neutral"
  | "skipped"
  | "stale"
  | "success"
  | "timed_out"
  | "in_progress"
  | "queued"
  | "requested"
  | "waiting"
  | "pending";
